=== DisaSoni/JS-XMLs/JLab6-DisaSoni/book.dtd
<!ELEMENT books (book*)>
<!ELEMENT book (ISBN, Title, Year, Laungage, Author)>
<!ATTLIST book
  id CDATA #REQUIRED
  >
  <!ELEMENT ISBN (#PCDATA)>
  <!ELEMENT Title (#PCDATA)>
  <!ELEMENT Year (#PCDATA)>
  <!ELEMENT Laungage (#PCDATA)>
  <!ELEMENT Author (#PCDATA)>

=== DisaSoni/JS-XMLs/JLab6-DisaSoni/book.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE books SYSTEM  "book.dtd">
<books>
    <book id="1">
        <ISBN>9781427038685</ISBN>
        <Title>War and Peace</Title>
        <Year>2018</Year>
        <Laungage>English</Laungage>
        <Author>Leo Nikolayevich Tolstoy</Author>

    </book>
    <book id="2">
        <ISBN>1841598976</ISBN>
        <Title> In Search of lost time</Title>
        <Year>2001</Year>
        <Laungage>English</Laungage>
        <Author>Marcel Proust</Author>

   </book>
</books>
